"""add_source_link

Revision ID: 0c7e681b8806
Revises: 772fe41b6a8f
Create Date: 2026-07-13 16:19:06.848779

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c7e681b8806'
down_revision: Union[str, None] = '772fe41b6a8f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('interval_min', sa.Integer(), nullable=False),
    sa.Column('interval_max', sa.Integer(), nullable=False),
    sa.Column('pause_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_post_time', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('processed_posts', sa.Column('source_link', sa.String(length=255), nullable=True))
    op.drop_index('ix_processed_posts_source_message_id', table_name='processed_posts')
    op.drop_constraint('uq_source_msg', 'processed_posts', type_='unique')
    op.create_unique_constraint('uq_post_source', 'processed_posts', ['source_channel_id', 'source_message_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_post_source', 'processed_posts', type_='unique')
    op.create_unique_constraint('uq_source_msg', 'processed_posts', ['source_channel_id', 'source_message_id'])
    op.create_index('ix_processed_posts_source_message_id', 'processed_posts', ['source_message_id'], unique=False)
    op.drop_column('processed_posts', 'source_link')
    op.drop_table('bot_settings')
    # ### end Alembic commands ###
