"""Initial

Revision ID: 2e6e82b0e7d9
Revises: 
Create Date: 2026-07-11 22:17:21.776149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e6e82b0e7d9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_posts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('source_channel_id', sa.BigInteger(), nullable=False),
    sa.Column('source_message_id', sa.BigInteger(), nullable=False),
    sa.Column('post_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('rewritten_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_channel_id', 'source_message_id', name='uq_source_msg')
    )
    op.create_index(op.f('ix_processed_posts_post_hash'), 'processed_posts', ['post_hash'], unique=False)
    op.create_index(op.f('ix_processed_posts_source_channel_id'), 'processed_posts', ['source_channel_id'], unique=False)
    op.create_index(op.f('ix_processed_posts_source_message_id'), 'processed_posts', ['source_message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_processed_posts_source_message_id'), table_name='processed_posts')
    op.drop_index(op.f('ix_processed_posts_source_channel_id'), table_name='processed_posts')
    op.drop_index(op.f('ix_processed_posts_post_hash'), table_name='processed_posts')
    op.drop_table('processed_posts')
    # ### end Alembic commands ###
