"""Add media support

Revision ID: 40887a090f12
Revises: c3d4e5f6a7b8
Create Date: 2026-07-13 12:20:25.145055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '40887a090f12'
down_revision: Union[str, None] = 'c3d4e5f6a7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('processed_posts', sa.Column('media_path', sa.String(length=512), nullable=True))
    op.add_column('processed_posts', sa.Column('media_type', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('processed_posts', 'media_type')
    op.drop_column('processed_posts', 'media_path')
    # ### end Alembic commands ###
